In [1]:
import torch

torch.tensor(19)

tensor(19)

In [2]:
torch.__version__

'2.5.1'

In [7]:
# scalar, no dimenion
scalar = torch.tensor(22)
scalar.shape, scalar.ndim

(torch.Size([]), 0)

In [11]:
# vector
vector = torch.tensor([1,2,3,4])

vector.shape, vector.ndim

(torch.Size([4]), 1)

In [13]:
matric = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

matric.ndim, matric.shape

(2, torch.Size([3, 3]))

In [15]:
tensor = torch.tensor([[[1,2,3],[4,5,6]],
                       [[7,8,9],[10,11,12]],
                       [[13,14,15],[16,17,18]]])

tensor.ndim

3

In [16]:
tensor.shape

torch.Size([3, 2, 3])

In [28]:
# random Tensors

random = torch.rand(1,3,4,5)
random


tensor([[[[0.5382, 0.2313, 0.4153, 0.0616, 0.5658],
          [0.7931, 0.6915, 0.3199, 0.6550, 0.9040],
          [0.1602, 0.3710, 0.0304, 0.8386, 0.6313],
          [0.7569, 0.1429, 0.7311, 0.4325, 0.7364]],

         [[0.0839, 0.8993, 0.4207, 0.7774, 0.4258],
          [0.1452, 0.5154, 0.7641, 0.3482, 0.9769],
          [0.3284, 0.2525, 0.6007, 0.3765, 0.3763],
          [0.4011, 0.6346, 0.3683, 0.3021, 0.6288]],

         [[0.4870, 0.3875, 0.6432, 0.8216, 0.9010],
          [0.3369, 0.6295, 0.6396, 0.5703, 0.1492],
          [0.4357, 0.7151, 0.1354, 0.8051, 0.7737],
          [0.9056, 0.3641, 0.2679, 0.4284, 0.6025]]]])

In [34]:
# range

tens = torch.arange(3,10, dtype=torch.float64)
tens.dtype

torch.float64

In [35]:
tens.type(torch.int32)

tensor([3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [46]:
torch.manual_seed(42)
ran = torch.rand(3,2,1)

ran

tensor([[[0.8823],
         [0.9150]],

        [[0.3829],
         [0.9593]],

        [[0.3904],
         [0.6009]]])

In [47]:
ran * 10

tensor([[[8.8227],
         [9.1500]],

        [[3.8286],
         [9.5931]],

        [[3.9045],
         [6.0090]]])

In [63]:
# Matrix multiplication

one = torch.rand(2,10)
two = torch.rand(2,10)

two


tensor([[0.9302, 0.6558, 0.0766, 0.8460, 0.3624, 0.3083, 0.0850, 0.0029, 0.6431,
         0.3908],
        [0.6947, 0.0897, 0.8712, 0.1330, 0.4137, 0.6044, 0.7581, 0.9037, 0.9555,
         0.1035]])

In [64]:
one

tensor([[0.9998, 0.5944, 0.6541, 0.0337, 0.1716, 0.3336, 0.5782, 0.0600, 0.2846,
         0.2007],
        [0.5014, 0.3139, 0.4654, 0.1612, 0.1568, 0.2083, 0.3289, 0.1054, 0.9192,
         0.4008]])

In [67]:
one.matmul(two.T)

tensor([[1.8742, 2.3800],
        [1.7413, 2.2584]])

In [66]:
one.shape  , two.T.shape

(torch.Size([2, 10]), torch.Size([10, 2]))

In [79]:
one = torch.rand(2,3,4)

two = torch.rand(2,3,4)

In [80]:
one.shape, two.shape

(torch.Size([2, 3, 4]), torch.Size([2, 3, 4]))

In [92]:
one.matmul(two)

tensor([[[1.1552, 0.5687, 1.2026],
         [1.0490, 0.4389, 0.8951],
         [0.7851, 0.3467, 0.4502]],

        [[0.5093, 1.0254, 0.9614],
         [0.8271, 1.8892, 1.9874],
         [0.3046, 0.6112, 0.4214]]])

In [87]:
two.shape

torch.Size([2, 3, 4])

In [90]:
two = two.reshape(2,4,3)

In [91]:
two.shape

torch.Size([2, 4, 3])

In [103]:
nes = torch.arange(1,11)

nes, nes.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [104]:
nes.reshape(1,10)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [105]:
nes

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
n = torch.stack([nes,nes,nes], dim=0)
n

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [112]:
n.squeeze()

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [113]:
n.shape

torch.Size([3, 10])

In [119]:
n.view(1,3,10).squeeze()

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [121]:
n.squeeze()

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [123]:


ram = torch.rand(2,3)

ram

tensor([[0.1836, 0.0991, 0.1583],
        [0.0066, 0.1142, 0.3764]])

In [124]:
ram.shape

torch.Size([2, 3])

In [130]:
ram.unsqueeze(dim=0).squeeze().shape

torch.Size([2, 3])

In [133]:
original = torch.tensor([[1,2,3],[4,5,6]])
original

tensor([[1, 2, 3],
        [4, 5, 6]])

In [134]:
original.shape, original.ndim

(torch.Size([2, 3]), 2)

In [164]:
da = torch.rand(2,3)

da ,da.shape, da.ndim

(tensor([[0.1642, 0.6212, 0.6378],
         [0.7740, 0.8801, 0.7784]]),
 torch.Size([2, 3]),
 2)

In [167]:
torch.reshape(da, (-1,))

tensor([0.1642, 0.6212, 0.6378, 0.7740, 0.8801, 0.7784])