In [12]:
# To create a randome tensors
# pass the dimension as parameter
import torch

random = torch.rand(size=(3,3))

random

tensor([[0.1638, 0.9707, 0.5345],
        [0.2831, 0.4085, 0.7013],
        [0.7336, 0.4962, 0.3858]])

In [14]:
#Dtype of a tensor can be found
# float32 is default typr of random tensors
random.dtype

torch.float32

In [18]:
# create a random tensor full of zeros

torch.zeros(4,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [19]:
# create a random tensor full of ones
torch.ones(4,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [24]:
# creating a tensor inside range

torch.arange(1,11,3)

tensor([ 1,  4,  7, 10])

In [26]:
# create a tensor like another

torch.zeros_like(random)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [27]:
torch.ones_like(random)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [32]:
torch.cuda.is_available()

False

In [45]:
float_32_tensor = torch.tensor([1.0,2.0,3.0,4.0,5.0], dtype=torch.float64, device='cpu', requires_grad=True)

In [38]:
float_32_tensor.dtype

torch.float64

In [44]:
float_32_tensor.device

device(type='cpu')

In [48]:
float_32_tensor.grad