In [1]:
# Pytorch Random Tensors
import torch

torch.tensor(10)

/Users/sachinmurali/Desktop/Pytorch/venv-pytorch/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:295: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


tensor(10)

## Why random Tensors ? 
  - many neural network start with full of random numbers, to better represent the data
  

In [3]:
random_tens = torch.rand(3,4)

random_tens

tensor([[0.8225, 0.6654, 0.4043, 0.1076],
        [0.8612, 0.6383, 0.7325, 0.8886],
        [0.9243, 0.4804, 0.9663, 0.8087]])

In [5]:
# dimension of tensor

random_tens.ndim

2

In [20]:
#  create a random tensor for image

random_tensor_image = torch.rand(size =(3,2,1))

random_tensor_image

tensor([[[0.1355],
         [0.4688]],

        [[0.7698],
         [0.7898]],

        [[0.0374],
         [0.8146]]])

In [22]:
random_tensor_image = torch.rand(size =(1,2,3))
random_tensor_image

tensor([[[0.7481, 0.8437, 0.9655],
         [0.7531, 0.5608, 0.2250]]])

In [23]:
random_tensor_image.ndim

3

In [28]:
torch.tensor()

TypeError: tensor() missing 1 required positional arguments: "data"