In [7]:
import torch

tensor = torch.rand(4, dtype=torch.float16)

tensor

tensor([0.8154, 0.6250, 0.7061, 0.9648], dtype=torch.float16)

In [8]:
tensor.dtype

torch.float16

In [13]:
tensor.shape,  tensor.device, tensor

(torch.Size([4]),
 device(type='cpu'),
 tensor([0.8154, 0.6250, 0.7061, 0.9648], dtype=torch.float16))

In [18]:
# Manipulating Tensors
# Addtion

new_one = torch.tensor([1, 2, 3, 4])

new_one +  10

# Subtraction

new_one - 10

new_one

tensor([1, 2, 3, 4])

In [21]:
tensor_one = torch.tensor([1, 2, 3, 4]) # 1 * 4
tensor_two  =  torch.tensor([5, 6, 7, 8]) # 1 * 4

tensor_one * tensor_two

tensor([ 5, 12, 21, 32])

In [22]:
# MAtrix multiplication

tensor_one.matmul(tensor_two)

tensor(70)

In [23]:
# also use @ symbol for matrix multiplication, but not recommended

tensor_one @ tensor_two

tensor(70)

In [24]:
# another method would be

torch.matmul(tensor_one, tensor_two)

tensor(70)

In [30]:
matrix_one = torch.tensor([[1, 2, 3],
                            [4, 5, 6],      # 4* 3
                            [7, 8, 9],
                            [7, 8, 9]])


matrix_two = torch.tensor([[1, 2, 3, 4],
                            [4, 5, 6, 5]
                           ])                # 2 * 4


torch.matmul(matrix_one, matrix_two)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x3 and 2x4)

In [31]:
matrix_one.T @ matrix_two.T

tensor([[ 58, 101],
        [ 68, 121],
        [ 78, 141]])

In [36]:
# Another method

matrix_one.T.mm(matrix_two.T)


tensor([[ 58, 101],
        [ 68, 121],
        [ 78, 141]])

In [45]:
torch.manual_seed(42)

torch.rand(3,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])