In [33]:
import torch

# Reshape

one = torch.arange(1,11)

one

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
one.shape

torch.Size([10])

In [35]:
two = one.reshape(1,1,10)
two

tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]])

In [36]:
two.shape

torch.Size([1, 1, 10])

In [43]:
two.view(1,10)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [45]:
two.view(1,10)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [54]:
# Stack the tensor

a = torch.tensor([1,2,3])

torch.stack([a,a,a], dim=1)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [60]:
TENSOR_ONE = torch.tensor([[1,2,3],
                          [4,5,6]])

TENSOR_TWO = torch.tensor([7,8,9])


torch.stack([TENSOR_ONE, TENSOR_ONE], dim=0)

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [62]:
x = torch.tensor([[1,2,3]])

x

tensor([[1, 2, 3]])

In [65]:
x = x.squeeze()

In [67]:
x.unsqueeze(0)

tensor([[1, 2, 3]])

In [69]:
x = torch.rand(1,2,3)
x

tensor([[[0.2459, 0.5884, 0.5051],
         [0.8095, 0.9489, 0.6119]]])

In [70]:
x.permute(2,1,0)

tensor([[[0.2459],
         [0.8095]],

        [[0.5884],
         [0.9489]],

        [[0.5051],
         [0.6119]]])

In [85]:
x = torch.arange(1,10)

x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
x.reshape(1,3,3)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])