In [33]:
import torch

# Reshape

one = torch.arange(1,11)

one

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
one.shape

torch.Size([10])

In [35]:
two = one.reshape(1,1,10)
two

tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]])

In [36]:
two.shape

torch.Size([1, 1, 10])

In [43]:
two.view(1,10)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [45]:
two.view(1,10)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])