In [79]:
import torch

torch.__version__

'2.5.1'

In [80]:
# tensor is basic building block of ml and dl algorithms
# It is used to represent info in numeric way

# Zero  dimensional tensor
# scalar
scalar = torch.tensor(10)

# shape tells , how the elements are arranged inside tensor


scalar.ndim, scalar.shape  # 0 dimansional tensor with shape : []

(0, torch.Size([]))

In [81]:
# to take out value out of tensor
num = scalar.item()
num

10

In [82]:
# vector - single dimension tensor
vector = torch.tensor([1,2,3,4])

vector.ndim, vector.shape #`1 dimansional tensor with shape : [4]

(1, torch.Size([4]))

In [83]:
# MATRIX -  2 dimensional tensor
MATRIX = torch.tensor([[1,2,3],
                       [1,2,3]])

MATRIX.ndim, MATRIX.shape, MATRIX.dtype



(2, torch.Size([2, 3]), torch.int64)

In [84]:
# Random Tensor
random_tensor = torch.rand(2,3)

random_tensor

tensor([[0.5688, 0.4151, 0.3445],
        [0.0404, 0.3157, 0.1651]])

In [85]:
random_tensor.ndim, random_tensor.shape, random_tensor.dtype

(2, torch.Size([2, 3]), torch.float32)

In [86]:
#Zeros and Ones
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [87]:
ones = torch.ones(2,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [88]:
# Range Tensors

range_tensor = torch.arange(1,11)
range_tensor, range_tensor.ndim, range_tensor.shape, range_tensor.dtype

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 1,
 torch.Size([10]),
 torch.int64)

In [89]:
# like tensor

zeros_like_tensor = torch.zeros_like(range_tensor)
one_like_tensor = torch.ones_like(range_tensor)
zeros_like_tensor, one_like_tensor

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [90]:
new = torch.tensor([1.,2.,3.,4.],
                   dtype=None, 
                   device = None,
                   requires_grad=False)

new, new.shape,new.ndim,new.dtype,new.device,new.grad

(tensor([1., 2., 3., 4.]),
 torch.Size([4]),
 1,
 torch.float32,
 device(type='cpu'),
 None)

In [91]:
one = torch.tensor([12.0])

one.dtype

torch.float32

In [92]:
one.type(torch.float16)

tensor([12.], dtype=torch.float16)

In [93]:
# manipulating tensor
# addition
tens = torch.rand(3)
tens

tensor([0.7965, 0.2064, 0.7736])

In [94]:
tens+tens

tensor([1.5930, 0.4128, 1.5471])

In [95]:
# elelment wies emultiplication
one = torch.rand(3,2)
two = torch.rand(2,3)

one, two

(tensor([[0.3010, 0.1323],
         [0.2549, 0.0090],
         [0.5814, 0.4451]]),
 tensor([[0.1374, 0.7821, 0.2403],
         [0.5525, 0.6432, 0.8075]]))

In [97]:
one.matmul(two)

tensor([[0.1144, 0.3205, 0.1791],
        [0.0400, 0.2051, 0.0685],
        [0.3258, 0.7410, 0.4991]])

In [98]:
one.mm(two)

tensor([[0.1144, 0.3205, 0.1791],
        [0.0400, 0.2051, 0.0685],
        [0.3258, 0.7410, 0.4991]])

In [103]:
test = torch.tensor([[1,2,3],[4,5,6]])

test

tensor([[1, 2, 3],
        [4, 5, 6]])

In [105]:
test.reshape(1,3,2)

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [111]:
z = test.view(1,2,3)
z[:,0] = 100
z

tensor([[[100, 100, 100],
         [  4,   5,   6]]])

In [112]:
test

tensor([[100, 100, 100],
        [  4,   5,   6]])

In [122]:
tester = torch.rand(1,1,10)

tester

tensor([[[0.6719, 0.3495, 0.5902, 0.3045, 0.5681, 0.5220, 0.2199, 0.5089,
          0.2513, 0.9937]]])

In [142]:
tester[0,0,0] =100

In [164]:
tester

tensor([[[5.0000e+02, 3.4955e-01, 5.9021e-01, 3.0445e-01, 5.6810e-01,
          5.2199e-01, 2.1989e-01, 5.0890e-01, 2.5135e-01, 9.9371e-01]]])

In [162]:
tester[0][0][0] = 500

In [163]:
tester

tensor([[[5.0000e+02, 3.4955e-01, 5.9021e-01, 3.0445e-01, 5.6810e-01,
          5.2199e-01, 2.1989e-01, 5.0890e-01, 2.5135e-01, 9.9371e-01]]])

In [150]:
torch.stack([tester,tester,tester],dim=0).shape

torch.Size([3, 1, 1, 10])

In [152]:
tester

tensor([[[200.0000,   0.3495,   0.5902,   0.3045,   0.5681,   0.5220,   0.2199,
            0.5089,   0.2513,   0.9937]]])

In [157]:
tester.squeeze().unsqueeze(dim=0).unsqueeze(dim=0)

tensor([[[200.0000,   0.3495,   0.5902,   0.3045,   0.5681,   0.5220,   0.2199,
            0.5089,   0.2513,   0.9937]]])

In [176]:
torch.manual_seed(42)
one= torch.rand(2,3)

torch.manual_seed(42)

two= torch.rand(2,3)

one, two

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]]),
 tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]]))

In [178]:
# device

device = "cuda" if torch.cuda.is_available() else "cpu"

In [181]:
torch.backends.mps.is_available()


True

In [184]:
torch.backends.mps.is_built()

True

In [185]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

In [186]:
device

'mps'

In [187]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='mps:0')

In [189]:
tensor.to(device)

tensor([1, 2, 3], device='mps:0')